/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.cad_is;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class CAD_Info extends javax.swing.JFrame {

    /**
     * Creates new form CAD_Info
     */
    
    
   
       ArrayList<String> Categorydetail=new ArrayList<String>(); //making arraylist of category for storing the category data
       ArrayList<Integer>AccessoriesID = new ArrayList<Integer>(); //making arraylist of accessories id
      

    
    public CAD_Info() {
        initComponents();
           setExtendedState(JFrame.MAXIMIZED_BOTH);
           this.setResizable(false);  //this will fix the size of the application   
           
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        about = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textsearch = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        save = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        category = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        range = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        insert = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        cleartable = new javax.swing.JButton();
        re = new javax.swing.JLabel();
        rec = new javax.swing.JTextField();
        available = new javax.swing.JButton();
        category1 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        Open = new javax.swing.JMenu();
        open = new javax.swing.JMenuItem();
        Close = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Help = new javax.swing.JMenuItem();
        About = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        about.setTitle("About");
        about.setBackground(new java.awt.Color(153, 0, 153));
        about.setBounds(new java.awt.Rectangle(500, 250, 0, 0));
        about.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        about.setMinimumSize(new java.awt.Dimension(500, 400));
        about.setResizable(false);
        about.setSize(new java.awt.Dimension(0, 0));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("ABOUT US");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 0));
        jLabel7.setText("The Car Accessories Detail is a software which store the ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 0));
        jLabel8.setText("records of car accessories along with their price. The user");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 0));
        jLabel9.setText("can handle the records easily by using this software.");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 0, 102));
        jLabel10.setText("Version: 1.0.0.0");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 0, 102));
        jLabel11.setText("Developed By:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 0, 102));
        jLabel12.setText("Amit Shrestha");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 102));
        jLabel13.setText("Bibek Kshetri");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 102));
        jLabel14.setText("Diwash Gurung");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 102));
        jLabel15.setText("Pratik Sherchan");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 102));
        jLabel16.setText("Sushil Kandel");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout aboutLayout = new javax.swing.GroupLayout(about.getContentPane());
        about.getContentPane().setLayout(aboutLayout);
        aboutLayout.setHorizontalGroup(
            aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(aboutLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        aboutLayout.setVerticalGroup(
            aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CAD_INFO");
        setBackground(new java.awt.Color(51, 0, 51));
        setForeground(new java.awt.Color(0, 0, 0));
        setIconImages(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CAR ACCESSORIES DETAILS");

        textsearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CAR ACCESSORIES DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Air Bag", "Comfort", "High",  new Integer(1000), "Toyota Motor Corporation"},
                { new Integer(2), "Carpet", "Decoration", "High",  new Integer(3000), "General Motors Company"},
                { new Integer(3), "Air Freshner", "Ambience", "Medium",  new Integer(500), "Volkswagen group"},
                { new Integer(4), "Seat Belt", "Vehicle Care", "High",  new Integer(2500), "Ford Motor Company"},
                { new Integer(5), "Seat Cover", "Decoration", "Low",  new Integer(200), "Honda Corporation"},
                { new Integer(6), "A/C Condenser", "Ambience", "Medium",  new Integer(1000), "Suzuki Motor Corporation"},
                { new Integer(7), "Mirror", "Vehicle Care", "Low",  new Integer(250), "Toyota Motor Corporation"},
                { new Integer(8), "Car Wheel Light", "Decoration", "High",  new Integer(3000), "General Motors Company"},
                { new Integer(9), "LED Ambient", "Ambience", "Medium",  new Integer(1500), "Volkswagen group"},
                { new Integer(10), "Car Moniter", "Media", "Low",  new Integer(700), "Ford Motor Company"},
                { new Integer(11), "Car Plush Seat", "Comfort", "Medium",  new Integer(1500), "Honda Corporation"},
                { new Integer(12), "Car Neck Pillow", "Comfort", "High",  new Integer(2500), "Suzuki Motor Corporation"}
            },
            new String [] {
                "Accessories Number", "Accessories Name", "Category", "Range", "Price", "Recommended By"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(save)
                .addContainerGap(772, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(save)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Accessories Number");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Accessories Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Price");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Category");

        category.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambience", "Comfort", "Media", "Decoration", "Vehicle Care" }));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Low");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Medium");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("High");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addGap(27, 27, 27)
                .addComponent(jRadioButton2)
                .addGap(32, 32, 32)
                .addComponent(jRadioButton3)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        range.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        range.setText("Range Level");

        no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noKeyTyped(evt);
            }
        });

        price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        insert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logout.setText("Log Out");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        cleartable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cleartable.setText("Clear Table");
        cleartable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleartableActionPerformed(evt);
            }
        });

        re.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        re.setText("Recommandation");

        rec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recActionPerformed(evt);
            }
        });

        available.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        available.setText("Available Accessories");
        available.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableActionPerformed(evt);
            }
        });

        category1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        category1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambience", "Comfort", "Media", "Decoration", "Vehicle Care" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(category1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(available)
                        .addGap(42, 42, 42)
                        .addComponent(textsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(268, 268, 268)))
                .addComponent(search)
                .addGap(158, 158, 158))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(re)
                                    .addComponent(insert)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(clear)
                                .addGap(54, 54, 54)
                                .addComponent(logout))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(range)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rec, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 8, Short.MAX_VALUE)))))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cleartable)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search)
                            .addComponent(textsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(category1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(available))))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(range)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(re)
                            .addComponent(rec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clear)
                            .addComponent(logout)
                            .addComponent(insert))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cleartable)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        Open.setText("File");

        open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        open.setText("Open");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        Open.add(open);

        Close.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });
        Open.add(Close);

        jMenuBar1.add(Open);

        jMenu2.setText("Help");

        Help.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        Help.setText("Help File");
        Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpActionPerformed(evt);
            }
        });
        jMenu2.add(Help);

        About.setText("About");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        jMenu2.add(About);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
        
        try{
            int id = Integer.parseInt(no.getText());
            int rowCount = jTable1.getRowCount();
            for(int i=0; i<rowCount;i++){
                AccessoriesID.add(Integer.parseInt(jTable1.getValueAt(i,0).toString()));
            }
            if(AccessoriesID.contains(id)){
                 JOptionPane.showMessageDialog(this,"Accessories ID already exist","Task Denied",JOptionPane.WARNING_MESSAGE);
            }
                    
           else if(no.getText().equals("") || name.getText().equals("") || price.getText().equals("")|| rec.getText().equals("")){  
                //if the textfield is empty, this will pass the warning message for taskfield empty.
                JFrame f = new JFrame();
                JOptionPane.showMessageDialog(f,"Please complete the field","Task Denied",JOptionPane.WARNING_MESSAGE);
            }else{
                    
                int s1 = Integer.parseInt(no.getText());
                String s2 = name.getText().toString();
                String s3 = category.getSelectedItem().toString();
                String s4 = "";
                int s5 = Integer.parseInt(price.getText());
                String s6 = rec.getText().toString();
               
                // extracting the data of textfield in table
               //extracting the data of jRadiobutton in table
               
                if(jRadioButton1.isSelected()){
                    s4 = jRadioButton1.getText().toString();
                 }else if(jRadioButton2.isSelected()){
                     s4 = jRadioButton2.getText().toString();
                 }else if(jRadioButton3.isSelected()){
                    s4 = jRadioButton3.getText().toString();
                  }  
                 
                
                 Categorydetail.add(s3); //adding the category in arraylist Categorydetail
                      
                    DefaultTableModel table = (DefaultTableModel)jTable1.getModel(); //making default table
                    jTable1.setModel(table); 
                    Object row[] = {s1,s2,s3,s4,s5,s6};  
                    table.addRow(row);  //storing the data of textfield in row of table
                                
                    JFrame f = new JFrame();
                    JOptionPane.showMessageDialog(f, "Data Successfully inserted", "Task successful", JOptionPane.INFORMATION_MESSAGE);
                    //poping the information message for successfull insertion of data
                    
                    no.setText("");
                    name.setText("");
                    rec.setText("");
                    price.setText("");
                    
                    //this will clear the textfield of accessories number, name, recommendation and price
                    
            }
           
            }catch(NumberFormatException e){
                    JFrame f = new JFrame();
                    JOptionPane.showMessageDialog(f, "Please enter correct input","Task Denied",JOptionPane.WARNING_MESSAGE);
            
            }catch(Exception ef){
                JFrame f = new JFrame();
                JOptionPane.showMessageDialog(f, "Something went wrong!!!","Task Denied",JOptionPane.WARNING_MESSAGE);
                
             }
                    
         
    }//GEN-LAST:event_insertActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:       
    }//GEN-LAST:event_noActionPerformed

    private void recActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        
        int p = JOptionPane.showConfirmDialog(null,"Are you sure want to clear the textfield?","Close",JOptionPane.YES_NO_OPTION);
            if(p==0){
            no.setText("");
            name.setText("");
            rec.setText("");
            price.setText("");
            }
        //clearing the textfield
        
    }//GEN-LAST:event_clearActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
            int p = JOptionPane.showConfirmDialog(null,"Do you want to logout?","Close",JOptionPane.YES_NO_OPTION);
            if(p==0){
            LogIn welcome = new LogIn();
            welcome.setVisible(true);
            dispose();
            }
        
        
    }//GEN-LAST:event_logoutActionPerformed

    private void cleartableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleartableActionPerformed
        // TODO add your handling code here:
        try{ 
            int p = JOptionPane.showConfirmDialog(null,"Are you sure want to clear the table?","Clear",JOptionPane.YES_NO_OPTION);
            if(p==0){
            DefaultTableModel dm = (DefaultTableModel)jTable1.getModel();
            dm.getDataVector().removeAllElements(); //it will remove all the data of table
            dm.fireTableDataChanged(); // notifies the JTable that the model has changed
            textsearch.setText("");
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "Table Successfully cleared", "Task successful", JOptionPane.INFORMATION_MESSAGE);
           
            }  
        }catch(Exception e){
            JFrame f = new JFrame();
            JOptionPane.showMessageDialog(f, "Something went wrong!!!","Task Denied",JOptionPane.WARNING_MESSAGE);
        }     
    }//GEN-LAST:event_cleartableActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        
            int p = JOptionPane.showConfirmDialog(null,"Are you sure want to save the data?","Save",JOptionPane.YES_NO_OPTION);
            if(p==0){
            String filename = JOptionPane.showInputDialog("Enter file name:"); //Asking user to give file name
            File file = new File(filename);
        try{
            FileOutputStream s = new FileOutputStream(file,true); 
    
            if(p==0){
            
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            
            
            for(int i = 0; i < jTable1.getRowCount();i++){
              
                bw.write( "Accessories No: " +  jTable1.getValueAt(i,0).toString()+ "    " +
                             "Accessories Name: " + jTable1.getValueAt(i,1).toString()+ "   " +
                             "Category: " + jTable1.getValueAt(i,2).toString()+ "   "+
                             "Range: " + jTable1.getValueAt(i,3).toString()+ "   "+
                             "Price: " + jTable1.getValueAt(i,4).toString()+ "   "+
                             "Recommended By: " + jTable1.getValueAt(i,5).toString());  //writing data in file
               bw.newLine();
               
               //writing in file using buffered writter and filewritter
            }
               
               bw.close();
               fw.close();
               //closing buffered writter and filewritter  
               
                JFrame f = new JFrame();
                JOptionPane.showMessageDialog(f, "Data Successfully saved", "Task successful", JOptionPane.INFORMATION_MESSAGE); 
               //displaying proper message
            }
        
            
           
            
        }catch(IOException e){
             Logger.getLogger(CAD_Info.class.getName()).log(Level.SEVERE,null,e);       
        }
            }
        
    }//GEN-LAST:event_saveActionPerformed

    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        // TODO add your handling code here:
        
            JFileChooser filechooser = new JFileChooser();  
            
            if(filechooser.showOpenDialog(null)==JFileChooser.APPROVE_OPTION){  //choosing file from dialouge box
                File file = filechooser.getSelectedFile(); //selecting the file
                String FileName = file.getAbsolutePath();
                Runtime open = Runtime.getRuntime();  //opening the file while running the project
                try{
                    Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler " + FileName ); //this will open the file while running the project
         
                }catch(FileNotFoundException ex){
                    Logger.getLogger(CAD_Info.class.getName()).log(Level.SEVERE,null,ex);
                }catch(IOException ex){
                      Logger.getLogger(CAD_Info.class.getName()).log(Level.SEVERE,null,ex);
                }
                }else{
                      JOptionPane.showMessageDialog(this,"Task Cancel","Message",JOptionPane.WARNING_MESSAGE);  
                }
            
            
        
                
    }//GEN-LAST:event_openActionPerformed

    private void HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpActionPerformed
        // TODO add your handling code here:
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+ "C:\\Users\\user\\Documents\\NetBeansProjects\\CAD_IS\\src\\main\\java\\com\\mycompany\\cad_is\\File saved\\help.doc");
            //opening the help document by giving its location
           
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"error");  
        }
        
    }//GEN-LAST:event_HelpActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        
         int p = JOptionPane.showConfirmDialog(null,"Are you sure want to close the system?","Close",JOptionPane.YES_NO_OPTION);
            if(p==0){
            System.exit(0);
            }
            //closing the application
    }//GEN-LAST:event_CloseActionPerformed

    private void noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noKeyTyped
        // TODO add your handling code here:
   
       
    }//GEN-LAST:event_noKeyTyped

    public void sort(int [] a){//passing array list as parameters
	for(int i=0;i<a.length;i++){
	int minVal = minimumValue(a,i);
	swap(a,minVal,i);
       
		
	}
	for(int i=0;i<a.length;i++){
		System.out.println(a[i]);
                
	}
	}
	public int minimumValue(int [] a, int form){
		int minVal = form;
		for(int i = form +1;i<a.length;i++){
		if(a[i]<a[minVal]){
			minVal = i;
		}
	}
            return minVal;		
    }
        public void swap(int [] a,int i,int j){
	int temp= a[i];
	a[i] = a[j];
	a[j] = temp;
    }
     
        
    
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
           
        int rowcount = jTable1.getRowCount();//get the row count of the table
        int [] a = new int [rowcount];//store the row count in array
        
        for (int i = 0; i<rowcount;i++){
            a[i]= Integer.parseInt(jTable1.getValueAt(i,4).toString());//extraces the value at index no. 4 of the table
           
        }
        sort(a);//call the sort function
        int low = 0;
        int high = (a.length-1);
        
        try{
        int price = Integer.parseInt(textsearch.getText());
        BinarySearch bi = new BinarySearch();
        int index = bi.binarySearch(a,low,high,price);
        
        if(index==-1){
             JOptionPane.showMessageDialog(null, 
                              "Search Not Found", 
                              "Task Denied", 
                              JOptionPane.WARNING_MESSAGE);
        }else{
                      
                      getAccessoriesName(price);
                     
        }
        }catch(ArrayIndexOutOfBoundsException ei){
                JOptionPane.showMessageDialog(null,"Something Wrong!!!","Task Denied",JOptionPane.ERROR_MESSAGE);
                       
                  
        }catch(Exception ex) {
                JOptionPane.showMessageDialog(null, "Invalid Input or Empty Table", "ERROR",
                         JOptionPane.ERROR_MESSAGE);
               }
  
      
    }//GEN-LAST:event_searchActionPerformed

    private void getAccessoriesName(int price){
        String pr = String.valueOf(price);
        for(int i=0;i<jTable1.getRowCount();i++){
            String t = jTable1.getValueAt(i,4).toString();
            if(t.equals(pr)){
                JOptionPane.showMessageDialog(null,"Accessories Number: " +jTable1.getValueAt(i,0).toString()  +"\n"+ "Accessories Name: " + jTable1.getValueAt(i,1).toString()+"\n"+
                    "Category: " + jTable1.getValueAt(i,2).toString()  +"\n"+ "Range: " + jTable1.getValueAt(i,3).toString() + "\n" + "Recommended By: "+
                        jTable1.getValueAt(i,5).toString()+"\n","Search Found",
                    JOptionPane.INFORMATION_MESSAGE );    
                break;
            
            }
        }
    }
    
    private void availableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableActionPerformed
        // TODO add your handling code here:
          //code for the search item by category
        //if the table is not empty 
        if (jTable1.getRowCount() != 0) {
            String categorySearch = (String) category1.getSelectedItem();
            int searchIndex = 2;//index where the category is present
            int rows = jTable1.getRowCount();
            int datarows = 0;
            int n = 1;

            for (int i = 0; i < rows; i++) {
                if ((jTable1.getValueAt(i, searchIndex)) == null) {
                    break;
                }
                datarows++;
            }

            String displayAccessories = "";
            for (int i = 0; i < datarows; i++) {
                if (((String) jTable1.getValueAt(i, searchIndex)).equals(categorySearch)) {
                    int accessoriesNameIndex = 1;//index for accessoriesName 
                    //if the category is found the accessories is added in the displayAccessories
                    displayAccessories += n + ". " + ((String) jTable1.getValueAt(i, accessoriesNameIndex)) + "\n";
                    n++;
                }
            }
            if (!"".equals(displayAccessories)) {
                //message is displayed if the searched category is available in the table
                JOptionPane.showMessageDialog(this, (n-1)+" Accessory from "+ categorySearch+ " is found \n"+ displayAccessories, "Search Found!!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                //message is displayed if the searched category is not available in the table
                JOptionPane.showMessageDialog(this, "Accessories From " + categorySearch + " Category is not Available!!", "Search Not Found", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            //message is displayed if the table is empty
            JOptionPane.showMessageDialog(this, "The Table is Empty!!!", "Message!!!", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_availableActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        // TODO add your handling code here:
        about.setVisible(true);
    }//GEN-LAST:event_AboutActionPerformed
    
           
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CAD_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CAD_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CAD_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CAD_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CAD_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JMenuItem Close;
    private javax.swing.JMenuItem Help;
    private javax.swing.JMenu Open;
    private javax.swing.JDialog about;
    private javax.swing.JButton available;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JComboBox<String> category1;
    private javax.swing.JButton clear;
    private javax.swing.JButton cleartable;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logout;
    private javax.swing.JTextField name;
    private javax.swing.JTextField no;
    private javax.swing.JMenuItem open;
    private javax.swing.JTextField price;
    private javax.swing.JLabel range;
    private javax.swing.JLabel re;
    private javax.swing.JTextField rec;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JTextField textsearch;
    // End of variables declaration//GEN-END:variables
}
